name: Quality assurance

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: make configure
      - name: Codestyle check
        run: make lint

  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master

