name: Quality assurance

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Prepare virtual environment
        run: make configure

      - name: Check code-style
        run: make lint

      - name: Check typings
        run: make typecheck

  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master
